
// Auto-generated from Sports Reference HTML snapshots.
// Do not edit by hand.

export interface SportsReferenceCoachEntry {
  school: string;
  coach: string;
  conference: string;
  since: string;
  seasonWins: number;
  seasonLosses: number;
  currentWins: number;
  currentLosses: number;
  careerWins: number;
  careerLosses: number;
  careerNcaaAppearances: number;
  careerSweetSixteens: number;
  careerFinalFours: number;
  careerTitles: number;
  age: number;
  almaMater: string;
}

export const SPORTS_REFERENCE_COACHES_2026: SportsReferenceCoachEntry[] = [
  {
    "school": "Long Beach State",
    "coach": "Chris Acker",
    "conference": "Big West",
    "since": "2024-25",
    "seasonWins": 0,
    "seasonLosses": 4,
    "currentWins": 7,
    "currentLosses": 29,
    "careerWins": 7,
    "careerLosses": 29,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 45,
    "almaMater": "University of Phoenix"
  },
  {
    "school": "Samford",
    "coach": "Lennie Acuff",
    "conference": "Southern",
    "since": "2025-26",
    "seasonWins": 3,
    "seasonLosses": 2,
    "currentWins": 3,
    "currentLosses": 2,
    "careerWins": 113,
    "careerLosses": 84,
    "careerNcaaAppearances": 1,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 60,
    "almaMater": "Shorter College"
  },
  {
    "school": "Belmont",
    "coach": "Casey Alexander",
    "conference": "MVC",
    "since": "2019-20",
    "seasonWins": 3,
    "seasonLosses": 0,
    "currentWins": 143,
    "currentLosses": 54,
    "careerWins": 280,
    "careerLosses": 174,
    "careerNcaaAppearances": 1,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 53,
    "almaMater": "Belmont"
  },
  {
    "school": "Nevada",
    "coach": "Steve Alford",
    "conference": "MWC",
    "since": "2019-20",
    "seasonWins": 3,
    "seasonLosses": 2,
    "currentWins": 116,
    "currentLosses": 77,
    "careerWins": 625,
    "careerLosses": 346,
    "careerNcaaAppearances": 13,
    "careerSweetSixteens": 4,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 60,
    "almaMater": "Indiana"
  },
  {
    "school": "UC-San Diego",
    "coach": "Clint Allard",
    "conference": "Big West",
    "since": "2025-26",
    "seasonWins": 4,
    "seasonLosses": 0,
    "currentWins": 4,
    "currentLosses": 0,
    "careerWins": 4,
    "careerLosses": 0,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 40,
    "almaMater": "UC San Diego"
  },
  {
    "school": "Oregon",
    "coach": "Dana Altman",
    "conference": "Big Ten",
    "since": "2010-11",
    "seasonWins": 4,
    "seasonLosses": 0,
    "currentWins": 374,
    "currentLosses": 162,
    "careerWins": 784,
    "careerLosses": 405,
    "careerNcaaAppearances": 17,
    "careerSweetSixteens": 5,
    "careerFinalFours": 1,
    "careerTitles": 0,
    "age": 67,
    "almaMater": "Eastern New Mexico"
  },
  {
    "school": "Harvard",
    "coach": "Tommy Amaker",
    "conference": "Ivy",
    "since": "2007-08",
    "seasonWins": 4,
    "seasonLosses": 1,
    "currentWins": 308,
    "currentLosses": 195,
    "careerWins": 484,
    "careerLosses": 334,
    "careerNcaaAppearances": 5,
    "careerSweetSixteens": 1,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 60,
    "almaMater": "Duke"
  },
  {
    "school": "Campbell",
    "coach": "John Andrzejek",
    "conference": "CAA",
    "since": "2025-26",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 2,
    "currentLosses": 2,
    "careerWins": 2,
    "careerLosses": 2,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 32,
    "almaMater": "Columbia"
  },
  {
    "school": "UC-Riverside",
    "coach": "Gus Argenal",
    "conference": "Big West",
    "since": "2025-26",
    "seasonWins": 2,
    "seasonLosses": 3,
    "currentWins": 2,
    "currentLosses": 3,
    "careerWins": 2,
    "careerLosses": 3,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 44,
    "almaMater": "UC Davis"
  },
  {
    "school": "McNeese State",
    "coach": "Bill Armstrong",
    "conference": "Southland",
    "since": "2025-26",
    "seasonWins": 3,
    "seasonLosses": 1,
    "currentWins": 3,
    "currentLosses": 1,
    "careerWins": 3,
    "careerLosses": 1,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 48,
    "almaMater": "UAB"
  },
  {
    "school": "Syracuse",
    "coach": "Adrian Autry",
    "conference": "ACC",
    "since": "2023-24",
    "seasonWins": 4,
    "seasonLosses": 0,
    "currentWins": 38,
    "currentLosses": 31,
    "careerWins": 38,
    "careerLosses": 31,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 53,
    "almaMater": "Syracuse"
  },
  {
    "school": "Rider",
    "coach": "Kevin Baggett",
    "conference": "MAAC",
    "since": "2012-13",
    "seasonWins": 1,
    "seasonLosses": 3,
    "currentWins": 207,
    "currentLosses": 205,
    "careerWins": 207,
    "careerLosses": 205,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 59,
    "almaMater": "Saint Joseph's"
  },
  {
    "school": "Florida International",
    "coach": "Jeremy Ballard",
    "conference": "CUSA",
    "since": "2018-19",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 100,
    "currentLosses": 126,
    "careerWins": 100,
    "careerLosses": 126,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 44,
    "almaMater": "Colgate"
  },
  {
    "school": "Tennessee",
    "coach": "Rick Barnes",
    "conference": "SEC",
    "since": "2015-16",
    "seasonWins": 4,
    "seasonLosses": 0,
    "currentWins": 236,
    "currentLosses": 109,
    "careerWins": 840,
    "careerLosses": 423,
    "careerNcaaAppearances": 29,
    "careerSweetSixteens": 10,
    "careerFinalFours": 1,
    "careerTitles": 0,
    "age": 71,
    "almaMater": "Lenoir-Rhyne"
  },
  {
    "school": "Oral Roberts",
    "coach": "Kory Barnett",
    "conference": "Summit",
    "since": "2025-26",
    "seasonWins": 2,
    "seasonLosses": 3,
    "currentWins": 2,
    "currentLosses": 3,
    "careerWins": 2,
    "careerLosses": 3,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 36,
    "almaMater": "Indiana"
  },
  {
    "school": "SIU-Edwardsville",
    "coach": "Brian Barone",
    "conference": "OVC",
    "since": "2019-20",
    "seasonWins": 3,
    "seasonLosses": 2,
    "currentWins": 89,
    "currentLosses": 105,
    "careerWins": 89,
    "careerLosses": 105,
    "careerNcaaAppearances": 1,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 47,
    "almaMater": "Marquette"
  },
  {
    "school": "Ole Miss",
    "coach": "Chris Beard",
    "conference": "SEC",
    "since": "2023-24",
    "seasonWins": 5,
    "seasonLosses": 0,
    "currentWins": 49,
    "currentLosses": 24,
    "careerWins": 220,
    "careerLosses": 97,
    "careerNcaaAppearances": 7,
    "careerSweetSixteens": 4,
    "careerFinalFours": 1,
    "careerTitles": 0,
    "age": 52,
    "almaMater": "Texas"
  },
  {
    "school": "Vermont",
    "coach": "John Becker",
    "conference": "AEC",
    "since": "2011-12",
    "seasonWins": 4,
    "seasonLosses": 1,
    "currentWins": 333,
    "currentLosses": 133,
    "careerWins": 333,
    "careerLosses": 133,
    "careerNcaaAppearances": 6,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 57,
    "almaMater": "Catholic"
  },
  {
    "school": "Saint Mary's",
    "coach": "Randy Bennett",
    "conference": "WCC",
    "since": "2001-02",
    "seasonWins": 4,
    "seasonLosses": 0,
    "currentWins": 566,
    "currentLosses": 222,
    "careerWins": 566,
    "careerLosses": 222,
    "careerNcaaAppearances": 11,
    "careerSweetSixteens": 1,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 62,
    "almaMater": "UC San Diego"
  },
  {
    "school": "Denver",
    "coach": "Tim Bergstraser",
    "conference": "Summit",
    "since": "2025-26",
    "seasonWins": 1,
    "seasonLosses": 3,
    "currentWins": 1,
    "currentLosses": 3,
    "careerWins": 1,
    "careerLosses": 3,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 38,
    "almaMater": "St. Cloud State"
  },
  {
    "school": "Sacramento State",
    "coach": "Mike Bibby",
    "conference": "Big Sky",
    "since": "2025-26",
    "seasonWins": 3,
    "seasonLosses": 3,
    "currentWins": 3,
    "currentLosses": 3,
    "careerWins": 3,
    "careerLosses": 3,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 47,
    "almaMater": "Arizona"
  },
  {
    "school": "NJIT",
    "coach": "Grant Billmeier",
    "conference": "AEC",
    "since": "2023-24",
    "seasonWins": 3,
    "seasonLosses": 2,
    "currentWins": 16,
    "currentLosses": 48,
    "careerWins": 17,
    "careerLosses": 48,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 41,
    "almaMater": "Seton Hall"
  },
  {
    "school": "Howard",
    "coach": "Kenneth Blakeney",
    "conference": "MEAC",
    "since": "2019-20",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 75,
    "currentLosses": 98,
    "careerWins": 75,
    "careerLosses": 98,
    "careerNcaaAppearances": 2,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 53,
    "almaMater": "Duke"
  },
  {
    "school": "Ohio",
    "coach": "Jeff Boals",
    "conference": "MAC",
    "since": "2019-20",
    "seasonWins": 1,
    "seasonLosses": 3,
    "currentWins": 115,
    "currentLosses": 79,
    "careerWins": 170,
    "careerLosses": 121,
    "careerNcaaAppearances": 1,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 53,
    "almaMater": "Ohio"
  },
  {
    "school": "Western Illinois",
    "coach": "Chad Boudreau",
    "conference": "OVC",
    "since": "2023-24",
    "seasonWins": 1,
    "seasonLosses": 4,
    "currentWins": 34,
    "currentLosses": 35,
    "careerWins": 34,
    "careerLosses": 35,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 53,
    "almaMater": "Hannibal-LaGrange"
  },
  {
    "school": "Colorado",
    "coach": "Tad Boyle",
    "conference": "Big 12",
    "since": "2010-11",
    "seasonWins": 4,
    "seasonLosses": 0,
    "currentWins": 316,
    "currentLosses": 204,
    "careerWins": 372,
    "careerLosses": 270,
    "careerNcaaAppearances": 6,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 62,
    "almaMater": "Kansas"
  },
  {
    "school": "Arkansas-Pine Bluff",
    "coach": "Solomon Bozeman",
    "conference": "SWAC",
    "since": "2021-22",
    "seasonWins": 0,
    "seasonLosses": 6,
    "currentWins": 36,
    "currentLosses": 94,
    "careerWins": 36,
    "careerLosses": 94,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 37,
    "almaMater": "Little Rock"
  },
  {
    "school": "Stephen F. Austin",
    "coach": "Matt Braeuer",
    "conference": "Southland",
    "since": "2025-26",
    "seasonWins": 4,
    "seasonLosses": 1,
    "currentWins": 4,
    "currentLosses": 1,
    "careerWins": 4,
    "careerLosses": 1,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 39,
    "almaMater": "Wichita State"
  },
  {
    "school": "Morgan State",
    "coach": "Kevin Broadus",
    "conference": "MEAC",
    "since": "2019-20",
    "seasonWins": 1,
    "seasonLosses": 4,
    "currentWins": 83,
    "currentLosses": 97,
    "careerWins": 120,
    "careerLosses": 122,
    "careerNcaaAppearances": 1,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 61,
    "almaMater": "Bowie State"
  },
  {
    "school": "Central Michigan",
    "coach": "Andy Bronkema",
    "conference": "MAC",
    "since": "2025-26",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 2,
    "currentLosses": 2,
    "careerWins": 2,
    "careerLosses": 2,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 41,
    "almaMater": "Cornerstone"
  },
  {
    "school": "Lamar",
    "coach": "Alvin Brooks",
    "conference": "Southland",
    "since": "2021-22",
    "seasonWins": 2,
    "seasonLosses": 1,
    "currentWins": 52,
    "currentLosses": 77,
    "careerWins": 106,
    "careerLosses": 161,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 66,
    "almaMater": "Lamar"
  },
  {
    "school": "Clemson",
    "coach": "Brad Brownell",
    "conference": "ACC",
    "since": "2010-11",
    "seasonWins": 4,
    "seasonLosses": 1,
    "currentWins": 296,
    "currentLosses": 197,
    "careerWins": 463,
    "careerLosses": 282,
    "careerNcaaAppearances": 8,
    "careerSweetSixteens": 2,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 57,
    "almaMater": "DePauw"
  },
  {
    "school": "Northern Arizona",
    "coach": "Shane Burcar",
    "conference": "Big Sky",
    "since": "2019-20",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 77,
    "currentLosses": 113,
    "careerWins": 77,
    "careerLosses": 113,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 53,
    "almaMater": "Ottawa"
  },
  {
    "school": "Northern Illinois",
    "coach": "Rashon Burno",
    "conference": "MAC",
    "since": "2021-22",
    "seasonWins": 2,
    "seasonLosses": 3,
    "currentWins": 41,
    "currentLosses": 88,
    "careerWins": 41,
    "careerLosses": 88,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 47,
    "almaMater": "DePaul"
  },
  {
    "school": "Chicago State",
    "coach": "Landon Bussie",
    "conference": "NEC",
    "since": "2025-26",
    "seasonWins": 0,
    "seasonLosses": 5,
    "currentWins": 0,
    "currentLosses": 5,
    "careerWins": 66,
    "careerLosses": 88,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 38,
    "almaMater": "Xavier (LA)"
  },
  {
    "school": "Vanderbilt",
    "coach": "Mark Byington",
    "conference": "SEC",
    "since": "2024-25",
    "seasonWins": 4,
    "seasonLosses": 0,
    "currentWins": 24,
    "currentLosses": 13,
    "careerWins": 237,
    "careerLosses": 146,
    "careerNcaaAppearances": 2,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 49,
    "almaMater": "UNC Wilmington"
  },
  {
    "school": "Northwestern State",
    "coach": "Rick Cabrera",
    "conference": "Southland",
    "since": "2023-24",
    "seasonWins": 1,
    "seasonLosses": 4,
    "currentWins": 26,
    "currentLosses": 43,
    "careerWins": 26,
    "careerLosses": 43,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 48,
    "almaMater": "Tennessee Tech"
  },
  {
    "school": "Utah State",
    "coach": "Jerrod Calhoun",
    "conference": "MWC",
    "since": "2024-25",
    "seasonWins": 4,
    "seasonLosses": 0,
    "currentWins": 30,
    "currentLosses": 8,
    "careerWins": 148,
    "careerLosses": 114,
    "careerNcaaAppearances": 1,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 44,
    "almaMater": "Cincinnati"
  },
  {
    "school": "Arkansas",
    "coach": "John Calipari",
    "conference": "SEC",
    "since": "2024-25",
    "seasonWins": 4,
    "seasonLosses": 1,
    "currentWins": 26,
    "currentLosses": 15,
    "careerWins": 881,
    "careerLosses": 278,
    "careerNcaaAppearances": 24,
    "careerSweetSixteens": 16,
    "careerFinalFours": 6,
    "careerTitles": 1,
    "age": 66,
    "almaMater": "Clarion"
  },
  {
    "school": "Pitt",
    "coach": "Jeff Capel III",
    "conference": "ACC",
    "since": "2018-19",
    "seasonWins": 4,
    "seasonLosses": 1,
    "currentWins": 118,
    "currentLosses": 108,
    "careerWins": 293,
    "careerLosses": 218,
    "careerNcaaAppearances": 4,
    "careerSweetSixteens": 1,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 50,
    "almaMater": "Duke"
  },
  {
    "school": "Florida Gulf Coast",
    "coach": "Patrick Chambers",
    "conference": "A-Sun",
    "since": "2022-23",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 52,
    "currentLosses": 50,
    "careerWins": 242,
    "careerLosses": 228,
    "careerNcaaAppearances": 1,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 54,
    "almaMater": "Philadelphia University"
  },
  {
    "school": "Le Moyne",
    "coach": "Nate Champion",
    "conference": "NEC",
    "since": "2023-24",
    "seasonWins": 2,
    "seasonLosses": 3,
    "currentWins": 26,
    "currentLosses": 43,
    "careerWins": 26,
    "careerLosses": 43,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 33,
    "almaMater": "Le Moyne"
  },
  {
    "school": "Bryant",
    "coach": "Jamion Christian",
    "conference": "AEC",
    "since": "2025-26",
    "seasonWins": 1,
    "seasonLosses": 3,
    "currentWins": 1,
    "currentLosses": 3,
    "careerWins": 148,
    "careerLosses": 164,
    "careerNcaaAppearances": 2,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 43,
    "almaMater": "Mount St. Mary's"
  },
  {
    "school": "Canisius",
    "coach": "Jim Christian",
    "conference": "MAAC",
    "since": "2024-25",
    "seasonWins": 2,
    "seasonLosses": 3,
    "currentWins": 5,
    "currentLosses": 31,
    "careerWins": 325,
    "careerLosses": 317,
    "careerNcaaAppearances": 2,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 60,
    "almaMater": "Rhode Island"
  },
  {
    "school": "Radford",
    "coach": "Zach Chu",
    "conference": "Big South",
    "since": "2025-26",
    "seasonWins": 2,
    "seasonLosses": 4,
    "currentWins": 2,
    "currentLosses": 4,
    "careerWins": 2,
    "careerLosses": 4,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 33,
    "almaMater": "Richmond"
  },
  {
    "school": "UTSA",
    "coach": "Austin Claunch",
    "conference": "American",
    "since": "2024-25",
    "seasonWins": 3,
    "seasonLosses": 2,
    "currentWins": 15,
    "currentLosses": 21,
    "careerWins": 105,
    "careerLosses": 82,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 36,
    "almaMater": "Emory"
  },
  {
    "school": "Hofstra",
    "coach": "Speedy Claxton",
    "conference": "CAA",
    "since": "2021-22",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 83,
    "currentLosses": 54,
    "careerWins": 83,
    "careerLosses": 54,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 47,
    "almaMater": "Hofstra"
  },
  {
    "school": "High Point",
    "coach": "Flynn Clayman",
    "conference": "Big South",
    "since": "2025-26",
    "seasonWins": 4,
    "seasonLosses": 1,
    "currentWins": 4,
    "currentLosses": 1,
    "careerWins": 6,
    "careerLosses": 2,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 37,
    "almaMater": "Troy"
  },
  {
    "school": "Portland State",
    "coach": "Jase Coburn",
    "conference": "Big Sky",
    "since": "2021-22",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 64,
    "currentLosses": 66,
    "careerWins": 64,
    "careerLosses": 66,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 42,
    "almaMater": "Arizona State"
  },
  {
    "school": "Northeastern",
    "coach": "Bill Coen",
    "conference": "CAA",
    "since": "2006-07",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 301,
    "currentLosses": 301,
    "careerWins": 301,
    "careerLosses": 301,
    "careerNcaaAppearances": 2,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 64,
    "almaMater": "Hamilton"
  },
  {
    "school": "Purdue Fort Wayne",
    "coach": "Jon Coffman",
    "conference": "Horizon",
    "since": "2014-15",
    "seasonWins": 2,
    "seasonLosses": 4,
    "currentWins": 200,
    "currentLosses": 159,
    "careerWins": 200,
    "careerLosses": 159,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 52,
    "almaMater": "Washington & Lee"
  },
  {
    "school": "Tennessee State",
    "coach": "Brian Collins",
    "conference": "OVC",
    "since": "2018-19",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 100,
    "currentLosses": 120,
    "careerWins": 100,
    "careerLosses": 120,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 41,
    "almaMater": "Belmont"
  },
  {
    "school": "Northwestern",
    "coach": "Chris Collins",
    "conference": "Big Ten",
    "since": "2013-14",
    "seasonWins": 4,
    "seasonLosses": 0,
    "currentWins": 198,
    "currentLosses": 190,
    "careerWins": 198,
    "careerLosses": 190,
    "careerNcaaAppearances": 3,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 51,
    "almaMater": "Duke"
  },
  {
    "school": "The Citadel",
    "coach": "Ed Conroy",
    "conference": "Southern",
    "since": "2006-07",
    "seasonWins": 1,
    "seasonLosses": 3,
    "currentWins": 76,
    "currentLosses": 147,
    "careerWins": 168,
    "careerLosses": 250,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 58,
    "almaMater": "The Citadel"
  },
  {
    "school": "Georgetown",
    "coach": "Ed Cooley",
    "conference": "Big East",
    "since": "2023-24",
    "seasonWins": 4,
    "seasonLosses": 0,
    "currentWins": 31,
    "currentLosses": 39,
    "careerWins": 365,
    "careerLosses": 261,
    "careerNcaaAppearances": 7,
    "careerSweetSixteens": 1,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 56,
    "almaMater": "Stonehill"
  },
  {
    "school": "Wagner",
    "coach": "Donald Copeland",
    "conference": "NEC",
    "since": "2022-23",
    "seasonWins": 0,
    "seasonLosses": 4,
    "currentWins": 46,
    "currentLosses": 49,
    "careerWins": 46,
    "careerLosses": 49,
    "careerNcaaAppearances": 1,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 41,
    "almaMater": "Seton Hall"
  },
  {
    "school": "Western Carolina",
    "coach": "Tim Craft",
    "conference": "Southern",
    "since": "2024-25",
    "seasonWins": 2,
    "seasonLosses": 2,
    "currentWins": 10,
    "currentLosses": 24,
    "careerWins": 198,
    "careerLosses": 190,
    "careerNcaaAppearances": 1,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 48,
    "almaMater": "Florida"
  },
  {
    "school": "Grambling",
    "coach": "Patrick Crarey II",
    "conference": "SWAC",
    "since": "2025-26",
    "seasonWins": 3,
    "seasonLosses": 2,
    "currentWins": 3,
    "currentLosses": 2,
    "careerWins": 17,
    "careerLosses": 19,
    "careerNcaaAppearances": 0,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 42,
    "almaMater": "La Sierra"
  },
  {
    "school": "UCLA",
    "coach": "Mick Cronin",
    "conference": "Big Ten",
    "since": "2019-20",
    "seasonWins": 4,
    "seasonLosses": 1,
    "currentWins": 142,
    "currentLosses": 65,
    "careerWins": 507,
    "careerLosses": 236,
    "careerNcaaAppearances": 15,
    "careerSweetSixteens": 4,
    "careerFinalFours": 1,
    "careerTitles": 0,
    "age": 54,
    "almaMater": "Cincinnati"
  },
  {
    "school": "Troy",
    "coach": "Scott Cross",
    "conference": "Sun Belt",
    "since": "2019-20",
    "seasonWins": 4,
    "seasonLosses": 2,
    "currentWins": 107,
    "currentLosses": 89,
    "careerWins": 332,
    "careerLosses": 250,
    "careerNcaaAppearances": 2,
    "careerSweetSixteens": 0,
    "careerFinalFours": 0,
    "careerTitles": 0,
    "age": 50,
    "almaMater": "UT Arlington"
  }
];

