import React from 'react';

// Shared styles extracted from App.tsx

export const styles: { [key: string]: React.CSSProperties } = {
    app: { 
        minHeight: '100vh', 
        fontFamily: "'Press Start 2P', cursive",
        color: '#000000',
    },
    toast: {
        position: 'fixed',
        bottom: '20px',
        left: '50%',
        transform: 'translateX(-50%)',
        backgroundColor: 'rgba(0,0,0,0.8)',
        color: 'white',
        padding: '10px 20px',
        borderRadius: '5px',
        zIndex: 2000,
        fontSize: '0.8rem',
        border: '2px solid white',
    },
    teamSelectionContainer: {
        backgroundColor: '#C0C0C0',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '100vh',
        padding: '20px',
    },
    title: {
        fontSize: '3rem',
        color: '#000000',
        textShadow: '4px 4px 0px #808080',
        marginBottom: '40px',
        textAlign: 'center',
    },
    header: {
        padding: '10px 15px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        position: 'sticky',
        top: 0,
        zIndex: 100,
    },
    headerRight: {
        flex: 1,
        display: 'flex',
        justifyContent: 'flex-end',
        alignItems: 'center',
        gap: '15px',
        fontSize: '0.8rem',
        textAlign: 'right',
    },
    seasonInfo: {
        textAlign: 'right',
        fontSize: '0.8rem',
    },
    conferenceLogoContainer: {
        flex: '0 0 auto',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '0 8px',
        minWidth: '110px',
    } as React.CSSProperties,
    conferenceLogoButton: {
        border: 'none',
        backgroundColor: 'transparent',
        cursor: 'pointer',
        padding: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100px',
        width: '110px',
    } as React.CSSProperties,
    conferenceLogoImage: {
        maxHeight: '96px',
        maxWidth: '96px',
        height: 'auto',
        width: 'auto',
        objectFit: 'contain',
        mixBlendMode: 'normal',
        filter: 'drop-shadow(0 1px 0 rgba(0,0,0,0.35))',
    } as React.CSSProperties,
    conferenceFallbackText: {
        fontSize: '0.75rem',
        opacity: 0.9,
        whiteSpace: 'nowrap',
    } as React.CSSProperties,
    logoBetween: {
        width: '180px',
        height: '90px',
        flex: '0 0 180px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    logoButton: {
        width: '100%',
        height: '100%',
        border: 'none',
        backgroundColor: 'transparent',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        padding: 0,
    },
    logoImage: {
        maxHeight: '80px',
        maxWidth: '80px',
        objectFit: 'contain',
    },
    sponsorLogoButton: {
        border: 'none',
        backgroundColor: 'transparent',
        cursor: 'pointer',
        padding: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '80px',
        height: '80px',
    },
    sponsorLogoImage: {
        maxHeight: '80px',
        maxWidth: '80px',
        objectFit: 'contain',
        filter: 'brightness(0) invert(1)',
        opacity: 0.95,
    },
    ncaaButton: {
        border: 'none',
        backgroundColor: 'transparent',
        cursor: 'pointer',
        padding: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '80px',
        height: '80px',
    },
    ncaaLogoImage: {
        maxHeight: '80px',
        maxWidth: '80px',
        height: 'auto',
        width: 'auto',
        objectFit: 'contain',
        opacity: 1,
    },
    coachButton: {
      fontFamily: "'Press Start 2P', cursive",
      fontSize: '0.6rem',
      padding: '4px 8px',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: '#FFFFFF #808080 #808080 #FFFFFF',
      backgroundColor: '#C0C0C0',
      color: '#000000',
      cursor: 'pointer',
    },
    sponsorDisplay: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '5px',
        fontSize: '0.8rem',
        fontWeight: 'bold',
        letterSpacing: '1px',
    },
    sponsorSlogan: {
        fontSize: '0.6rem',
        fontStyle: 'italic',
        letterSpacing: '1px',
        opacity: 0.8,
    },
    searchBarRow: {
        display: 'flex',
        gap: '10px',
        marginTop: '10px',
        alignItems: 'center',
    },
    searchInput: {
        flex: '1 1 auto',
        padding: '6px 8px',
        borderRadius: '4px',
        border: '1px solid #bdbdbd',
        fontSize: '0.7rem',
    },
    clearFiltersButton: {
        border: '1px solid #8a8a8a',
        borderRadius: '4px',
        backgroundColor: '#f2f2f2',
        fontSize: '0.65rem',
        padding: '6px 10px',
        cursor: 'pointer',
        height: '30px',
    },
    recruitFiltersRow: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '10px',
        marginTop: '10px',
    },
    filterControl: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        fontSize: '0.6rem',
        flex: '1 1 150px',
    },
    recruitingSummaryGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
        gap: '10px',
        margin: '15px 0',
    },
    recruitingSummaryCard: {
        border: '1px solid #d0d0d0',
        borderRadius: '6px',
        padding: '10px',
        backgroundColor: '#f9f9f9',
        fontSize: '0.65rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    trainingSummaryGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
        gap: '10px',
        margin: '15px 0',
    },
    trainingSummaryCard: {
        border: '1px solid #d0d0d0',
        borderRadius: '6px',
        padding: '10px',
        backgroundColor: '#f1f8e9',
        fontSize: '0.65rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    trainingSummaryMeta: {
        fontSize: '0.55rem',
        color: '#555',
        margin: 0,
    },
    interestCell: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    interestBarTrack: {
        width: '100%',
        height: '6px',
        backgroundColor: '#e0e0e0',
        borderRadius: '999px',
        overflow: 'hidden',
    },
    interestBarFill: {
        height: '100%',
        borderRadius: '999px',
    },
    interestBadge: {
        display: 'flex',
        justifyContent: 'space-between',
        fontSize: '0.55rem',
        fontWeight: 'bold',
    },
    financialHealthRow: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '10px',
        margin: '10px 0 20px',
    },
    healthCard: {
        border: '1px solid #d0d0d0',
        borderRadius: '6px',
        padding: '10px',
        backgroundColor: '#f8f8f8',
        fontSize: '0.65rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    nilInfoBanner: {
        backgroundColor: '#fff7e6',
        border: '1px solid #ffcc80',
        borderRadius: '4px',
        padding: '8px 10px',
        fontSize: '0.6rem',
        marginBottom: '12px',
        color: '#6d4c41',
    },
    nilBudgetMeta: {
        fontSize: '0.55rem',
        color: '#555',
        margin: '4px 0',
    },
    nilBudgetMeterTrack: {
        width: '100%',
        height: '6px',
        backgroundColor: '#e0e0e0',
        borderRadius: '999px',
        overflow: 'hidden',
    },
    nilBudgetMeterFill: {
        height: '100%',
        borderRadius: '999px',
        backgroundColor: '#1b5e20',
        transition: 'width 0.3s ease',
    },
    nilStatusPill: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '4px 8px',
        borderRadius: '999px',
        fontSize: '0.55rem',
        fontWeight: 'bold',
    },
    nilInsightText: {
        fontSize: '0.5rem',
        margin: '4px 0 0 0',
        color: '#555',
    },
    nilTermHelper: {
        fontSize: '0.5rem',
        marginTop: '4px',
        color: '#8d6e63',
    },
    nilOutlookBarTrack: {
        width: '100%',
        height: '6px',
        backgroundColor: '#e0e0e0',
        borderRadius: '999px',
        overflow: 'hidden',
    },
    nilOutlookBarFill: {
        height: '100%',
        borderRadius: '999px',
        backgroundColor: '#1b5e20',
        transition: 'width 0.3s ease',
    },
    nilHistoryPanel: {
        border: '1px solid #e0e0e0',
        borderRadius: '6px',
        backgroundColor: '#fdf7ff',
        padding: '10px',
        maxHeight: '180px',
        overflowY: 'auto',
    },
    nilHistoryList: {
        listStyle: 'none',
        paddingLeft: 0,
        margin: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        fontSize: '0.6rem',
    },
    nilHistoryItem: {
        borderLeft: '3px solid #9c27b0',
        paddingLeft: '8px',
        color: '#4a148c',
    },
    positionDepthRow: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
        marginBottom: '10px',
        fontSize: '0.65rem',
    },
    positionDepthPill: {
        border: '1px solid #d0d0d0',
        borderRadius: '4px',
        padding: '2px 6px',
        backgroundColor: '#f7f7f7',
    },
    healthMeta: {
        fontSize: '0.55rem',
        margin: 0,
        color: '#555',
    },
    revenueMixGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
        gap: '8px',
        marginBottom: '15px',
    },
    revenueMixCard: {
        border: '1px solid #e0e0e0',
        borderRadius: '6px',
        padding: '8px',
        fontSize: '0.6rem',
        backgroundColor: '#ffffff',
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    revenueMixMeta: {
        fontSize: '0.55rem',
        margin: 0,
        color: '#666',
    },
    investmentGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(210px, 1fr))',
        gap: '10px',
        marginBottom: '20px',
    },
    investmentCard: {
        border: '1px solid #d0d0d0',
        borderRadius: '6px',
        padding: '10px',
        backgroundColor: '#f4f6ff',
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        fontSize: '0.6rem',
    },
    investmentMeta: {
        fontSize: '0.55rem',
        fontStyle: 'italic',
        color: '#333',
        margin: 0,
    },
    tableLinkButton: {
        background: 'none',
        border: 'none',
        padding: 0,
        color: '#0044cc',
        textDecoration: 'underline',
        cursor: 'pointer',
        fontFamily: "'Press Start 2P', cursive",
        fontSize: '0.6rem',
    },
    tableSortButton: {
        background: 'none',
        border: 'none',
        padding: 0,
        color: 'inherit',
        cursor: 'pointer',
        fontFamily: "'Press Start 2P', cursive",
        fontSize: '0.55rem',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
    },
    kpiGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
        gap: '10px',
        marginBottom: '20px',
    },
    kpiCard: {
        border: '1px solid #d1d1d1',
        borderRadius: '6px',
        padding: '10px',
        backgroundColor: '#fefefe',
        fontSize: '0.6rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    kpiMeta: {
        fontSize: '0.55rem',
        color: '#666',
        margin: 0,
    },
    coachModalGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: '12px',
        marginBottom: '15px',
    },
    coachModalCard: {
        border: '1px solid #d0d0d0',
        borderRadius: '6px',
        padding: '10px',
        backgroundColor: '#f9f9f9',
        fontSize: '0.65rem',
    },
    modalList: {
        listStyle: 'none',
        padding: 0,
        margin: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    renameRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        marginTop: '8px',
    },
    renameInput: {
        flex: 1,
        padding: '6px',
        border: '1px solid #ccc',
        borderRadius: '4px',
        fontFamily: "'Press Start 2P', cursive",
        fontSize: '0.7rem',
    },
    autoTrainingToggleRow: {
        border: '1px dashed #9e9e9e',
        padding: '10px',
        borderRadius: '6px',
        marginBottom: '15px',
        backgroundColor: '#f5f5f5',
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    autoTrainingLogContainer: {
        marginTop: '15px',
        padding: '10px',
        border: '1px solid #cccccc',
        borderRadius: '6px',
        backgroundColor: '#fafafa',
    },
    autoTrainingLogList: {
        listStyle: 'none',
        paddingLeft: 0,
        fontSize: '0.6rem',
        maxHeight: '120px',
        overflowY: 'auto',
        margin: 0,
    },
    autoTrainingLogEmpty: {
        fontSize: '0.6rem',
        color: '#555',
        margin: 0,
    },
    pricePresetRow: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '10px',
        marginBottom: '10px',
    },
    presetButton: {
        flex: '1 1 200px',
        minWidth: '200px',
        border: '2px solid #9e9e9e',
        padding: '10px',
        borderRadius: '6px',
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        fontSize: '0.6rem',
        cursor: 'pointer',
    },
    scenarioCard: {
        border: '2px solid #c0c0c0',
        borderRadius: '6px',
        padding: '12px',
        backgroundColor: '#f7f7f7',
        marginBottom: '15px',
    },
    scenarioRow: {
        display: 'flex',
        justifyContent: 'space-between',
        fontSize: '0.65rem',
        marginBottom: '6px',
    },
    sentimentGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
        gap: '6px',
        marginTop: '10px',
    },
    sentimentPill: {
        border: '1px solid #d0d0d0',
        borderRadius: '999px',
        padding: '6px 10px',
        fontSize: '0.55rem',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    weeklyMeters: {
        marginTop: '15px',
        display: 'flex',
        flexWrap: 'wrap',
        gap: '10px',
    },
    resourceMeterCard: {
        flex: '1 1 200px',
        minWidth: '200px',
        border: '1px solid #d0d0d0',
        borderRadius: '6px',
        padding: '10px',
        backgroundColor: '#fdfdfd',
    },
    resourceMeterHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        fontSize: '0.6rem',
        marginBottom: '6px',
    },
    resourceMeterTrack: {
        width: '100%',
        height: '8px',
        backgroundColor: '#e0e0e0',
        borderRadius: '999px',
        overflow: 'hidden',
    },
    resourceMeterFill: {
        height: '100%',
        borderRadius: '999px',
    },
    resourceMeterMeta: {
        fontSize: '0.55rem',
        marginTop: '6px',
        color: '#444',
    },
    modalSubheading: {
        fontSize: '0.75rem',
        marginTop: '15px',
        marginBottom: '6px',
        textTransform: 'uppercase',
        letterSpacing: '1px',
    },
    sponsorGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
        gap: '10px',
        marginTop: '10px',
    },
    sponsorCard: {
        borderWidth: '2px',
        borderStyle: 'solid',
        borderColor: '#CCCCCC',
        borderRadius: '4px',
        padding: '15px',
        marginBottom: '10px',
        backgroundColor: '#F5F5F5',
        fontSize: '0.6rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '5px',
    },
    jobOfferCard: {
        border: '2px solid #808080',
        padding: '10px',
        marginBottom: '10px',
        backgroundColor: '#E0E0E0',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    sponsorModalContent: {
        backgroundColor: '#C0C0C0',
        padding: '20px',
        border: '4px solid',
        borderColor: '#FFFFFF #808080 #808080 #FFFFFF',
        width: '95%',
        maxWidth: '1200px',
        maxHeight: '90vh',
        overflowY: 'auto',
        position: 'relative',
    },
    sponsorTableHeader: {
        textTransform: 'uppercase',
        letterSpacing: '1px',
        fontSize: '0.6rem',
    },
    sponsorTableRow: {
        transition: 'background-color 0.2s ease',
    },
    mainContentArea: {
        padding: '10px',
        backgroundColor: '#C0C0C0'
    },
    navAndActionsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        marginBottom: '10px',
        position: 'sticky',
        top: 70,
        zIndex: 90,
        backgroundColor: '#C0C0C0',
        padding: '10px 0',
    },
    navRow: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(100px, 1fr))',
        gap: '10px',
    },
    actionsRow: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(100px, 1fr))',
        gap: '10px',
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '10px',
        width: '100%',
        maxWidth: '1200px',
    },
    button: {
        fontFamily: "'Press Start 2P', cursive",
        fontSize: '0.8rem',
        padding: '10px',
        borderWidth: '3px',
        borderStyle: 'solid',
        borderColor: '#FFFFFF #808080 #808080 #FFFFFF',
        backgroundColor: '#C0C0C0',
        color: '#000000',
        cursor: 'pointer',
        textOverflow: 'ellipsis',
        overflow: 'hidden',
        whiteSpace: 'pre-wrap',
    },
    content: {
        padding: '15px',
        backgroundColor: '#FFFFFF',
        borderRadius: '8px',
        boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
        position: 'relative',
    },
    tableContainer: {
        overflowX: 'auto',
    },
    table: {
        width: '100%',
        borderCollapse: 'separate',
        borderSpacing: '0',
        fontSize: '12px',
        color: '#0f172a',
        minWidth: '600px',
        background: '#f8fafc',
        border: '2px solid #0f172a',
        borderRadius: '6px',
        overflow: 'hidden',
        boxShadow: '4px 4px 0 #0f172a',
    },
    th: {
        padding: '12px 14px',
        borderBottom: '2px solid #0f172a',
        textAlign: 'left',
        fontWeight: 900,
        fontSize: '14px',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    td: {
        padding: '10px 12px',
        borderBottom: '1px solid #e2e8f0',
        verticalAlign: 'middle',
        color: '#0f172a',
        fontWeight: 600,
    },
    teamCell: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        minWidth: 0,
    },
    teamLogoWrapper: {
        flexShrink: 0,
    },
    teamNameBlock: {
        display: 'flex',
        flexDirection: 'column',
        minWidth: 0,
    },
    teamViaText: {
        fontSize: '0.62rem',
        color: '#555',
    },
    inlineRowAction: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
    },
    select: {
        fontFamily: "'Inter', system-ui, sans-serif",
        fontSize: '12px',
        fontWeight: 700,
        padding: '6px 10px',
        border: '2px solid #0f172a',
        borderRadius: '6px',
        backgroundColor: '#ffffff',
        color: '#0f172a',
        boxShadow: '2px 2px 0 #0f172a',
        cursor: 'pointer',
    },
    pullButton: {
      fontFamily: "'Inter', system-ui, sans-serif",
      fontSize: '10px',
      fontWeight: 900,
      padding: '4px 8px',
      border: '2px solid #0f172a',
      borderRadius: '4px',
      backgroundColor: '#fca5a5',
      color: '#0f172a',
      boxShadow: '2px 2px 0 #0f172a',
      cursor: 'pointer',
    },
    recruitingHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '15px',
        fontSize: '0.7rem'
    },
    recruitingThead: {
        fontSize: '0.75rem',
    },
    linkButton: {
        background: 'none',
        border: 'none',
        color: '#111827',
        textDecoration: 'none',
        cursor: 'pointer',
        fontFamily: "'Press Start 2P', cursive",
        fontSize: '0.6rem',
        padding: 0,
    },
    actionGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '4px',
    },
    smallButton: {
      fontFamily: "'Inter', system-ui, sans-serif",
      fontSize: '10px',
      fontWeight: 800,
      padding: '4px 8px',
      border: '2px solid #0f172a',
      borderRadius: '4px',
      backgroundColor: '#ffffff',
      color: '#0f172a',
      boxShadow: '2px 2px 0 #0f172a',
      cursor: 'pointer',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
    },
    conferenceHubOverlay: {
        position: 'fixed',
        inset: 0,
        zIndex: 2000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '16px',
        backgroundColor: 'rgba(15,23,42,0.80)',
        backgroundImage:
            'repeating-linear-gradient(0deg, rgba(255,255,255,0.05), rgba(255,255,255,0.05) 1px, transparent 1px, transparent 3px), repeating-linear-gradient(90deg, rgba(255,255,255,0.04), rgba(255,255,255,0.04) 1px, transparent 1px, transparent 3px)',
    } as React.CSSProperties,
    modalContent: {
        backgroundColor: '#C0C0C0',
        padding: '20px',
        border: '4px solid',
        borderColor: '#FFFFFF #808080 #808080 #FFFFFF',
        width: '90%',
        maxWidth: '500px',
        maxHeight: '90vh',
        overflowY: 'auto',
        position: 'relative',
    },
    modalCloseButton: {
        position: 'absolute',
        top: '5px',
        right: '5px',
        fontFamily: "'Press Start 2P', cursive",
        backgroundColor: '#C0C0C0',
        border: '2px solid',
        borderColor: '#FFFFFF #808080 #808080 #FFFFFF',
        width: '25px',
        height: '25px',
        cursor: 'pointer',
    },
    conferenceHubModalContent: {
        width: '100%',
        maxWidth: '1560px',
        maxHeight: '95vh',
        background: '#f8fafc',
        borderRadius: '8px',
        overflowY: 'auto',
        boxShadow: '10px 10px 0 #0f172a',
        border: '4px solid #0f172a',
        display: 'flex',
        flexDirection: 'column',
        position: 'relative',
    } as React.CSSProperties,
    conferenceHubCloseButton: {
        position: 'absolute',
        top: '10px',
        right: '10px',
        fontFamily: "'Press Start 2P', cursive",
        backgroundColor: '#fde047',
        border: '2px solid #0f172a',
        width: '30px',
        height: '30px',
        cursor: 'pointer',
        boxShadow: '2px 2px 0 #0f172a',
    } as React.CSSProperties,
    conferenceHubHeader: {
        padding: '16px 18px',
        borderBottom: '4px solid #0f172a',
        background: '#e2e8f0',
        position: 'relative',
        display: 'flex',
        alignItems: 'flex-start',
        gap: '14px',
    } as React.CSSProperties,
    conferenceHubLogo: {
        maxHeight: '72px',
        maxWidth: '220px',
        objectFit: 'contain',
        mixBlendMode: 'normal',
        filter: 'drop-shadow(0 1px 0 rgba(0,0,0,0.35))',
    } as React.CSSProperties,
    conferenceHubHeaderText: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        flex: 1,
        minWidth: 0,
    } as React.CSSProperties,
    conferenceHubTitle: {
        fontSize: '1.05rem',
        lineHeight: 1.15,
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    } as React.CSSProperties,
    conferenceHubSubtitle: {
        fontSize: '0.6rem',
        opacity: 0.85,
    } as React.CSSProperties,
    conferenceHubHeaderActions: {
        display: 'flex',
        gap: '8px',
        alignItems: 'center',
    } as React.CSSProperties,
    conferenceHubSelectLabel: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        fontSize: '0.55rem',
        fontWeight: 900,
        color: '#0f172a',
        whiteSpace: 'nowrap',
    } as React.CSSProperties,
    conferenceHubSelect: {
        fontFamily: "'Press Start 2P', cursive",
        fontSize: '0.55rem',
        padding: '8px 10px',
        borderRadius: '6px',
        border: '2px solid #0f172a',
        background: '#ffffff',
        color: '#0f172a',
        boxShadow: '2px 2px 0 rgba(15,23,42,0.35)',
        cursor: 'pointer',
        maxWidth: '240px',
    } as React.CSSProperties,
    conferenceHubActionButton: {
        fontFamily: "'Press Start 2P', cursive",
        fontSize: '0.55rem',
        padding: '8px 10px',
        borderRadius: '6px',
        border: '2px solid #0f172a',
        background: '#fde047',
        color: '#0f172a',
        boxShadow: '2px 2px 0 #0f172a',
        cursor: 'pointer',
        whiteSpace: 'nowrap',
    } as React.CSSProperties,
    conferenceHubHeaderStatsRow: {
        marginTop: '10px',
        display: 'flex',
        flexWrap: 'wrap',
        gap: '10px',
    } as React.CSSProperties,
    conferenceHubStatPill: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '8px',
        padding: '6px 10px',
        borderRadius: '6px',
        border: '2px solid #0f172a',
        boxShadow: '2px 2px 0 #0f172a',
        fontWeight: 900,
        fontSize: '0.55rem',
        whiteSpace: 'nowrap',
    } as React.CSSProperties,
    conferenceHubStatLabel: {
        fontSize: '0.45rem',
        letterSpacing: '0.06em',
        textTransform: 'uppercase',
        opacity: 0.85,
    } as React.CSSProperties,
    conferenceHubStatValue: {
        fontSize: '0.6rem',
        fontWeight: 900,
    } as React.CSSProperties,
    conferenceHubStatPillDark: {
        background: '#111827',
        color: '#ffffff',
    } as React.CSSProperties,
    conferenceHubStatPillBlue: {
        background: '#dbeafe',
        color: '#1d4ed8',
    } as React.CSSProperties,
    conferenceHubStatPillGreen: {
        background: '#dcfce7',
        color: '#166534',
    } as React.CSSProperties,
    conferenceHubStatPillAmber: {
        background: '#fff7ed',
        color: '#9a3412',
    } as React.CSSProperties,
    conferenceHubStatPillPurple: {
        background: '#f5f3ff',
        color: '#5b21b6',
    } as React.CSSProperties,
    conferenceHubTabs: {
        display: 'flex',
        gap: '8px',
        flexWrap: 'wrap',
        padding: '12px 18px 0',
        marginBottom: '12px',
    } as React.CSSProperties,
    conferenceHubTabButton: {
        fontFamily: "'Press Start 2P', cursive",
        fontSize: '0.6rem',
        padding: '8px 10px',
        borderRadius: '6px',
        border: '2px solid #0f172a',
        background: '#ffffff',
        color: '#0f172a',
        boxShadow: '2px 2px 0 rgba(15,23,42,0.35)',
        cursor: 'pointer',
    } as React.CSSProperties,
    conferenceHubTabButtonActive: {
        background: '#fde047',
        color: '#0f172a',
        boxShadow: '2px 2px 0 #0f172a',
    } as React.CSSProperties,
    conferenceHubBody: {
        flex: 1,
        overflowY: 'auto',
        padding: '0 18px 18px',
    } as React.CSSProperties,
    conferenceHubGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
        gap: '12px',
    } as React.CSSProperties,
    conferenceHubGridAuto: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
        gap: '12px',
    } as React.CSSProperties,
    conferenceHubPanel: {
        background: '#f8fafc',
        borderRadius: '6px',
        border: '2px solid #0f172a',
        boxShadow: '4px 4px 0 #0f172a',
        padding: '10px',
        minHeight: '260px',
    } as React.CSSProperties,
    conferenceHubPanelTitle: {
        fontSize: '0.65rem',
        marginBottom: '10px',
        padding: '8px 10px',
        borderRadius: '6px',
        background: '#111827',
        color: '#ffffff',
        border: '2px solid #0f172a',
        boxShadow: '2px 2px 0 #0f172a',
    } as React.CSSProperties,
    conferenceHubPanelSubTitle: {
        fontSize: '0.5rem',
        opacity: 0.85,
        marginBottom: '6px',
    } as React.CSSProperties,
    conferenceHubTable: {
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
        fontSize: '0.5rem',
    } as React.CSSProperties,
    conferenceHubTableScroll: {
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
        fontSize: '0.5rem',
        // Removed maxHeight/overflow to allow full extension
        paddingRight: '6px',
    } as React.CSSProperties,
    conferenceStandingsHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '10px',
        padding: '10px 10px',
        borderRadius: '6px',
        border: '2px solid #0f172a',
        background: '#e2e8f0',
        boxShadow: '2px 2px 0 #0f172a',
        fontSize: '0.55rem',
        fontWeight: 900,
        marginBottom: '10px',
    } as React.CSSProperties,
    conferenceStandingsScroll: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        // Removed fixed height/scroll to allow full extension
        paddingRight: '6px',
    } as React.CSSProperties,
    conferenceStandingsRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '10px',
        padding: '12px 12px',
        borderRadius: '8px',
        border: '2px solid #0f172a',
        background: '#ffffff',
        boxShadow: '4px 4px 0 #0f172a',
    } as React.CSSProperties,
    conferenceStandingsRowUser: {
        background: '#eff6ff',
        borderColor: '#1d4ed8',
        boxShadow: '4px 4px 0 #1d4ed8',
    } as React.CSSProperties,
    conferenceStandingsRowLeader: {
        background: '#ecfdf5',
        borderColor: '#16a34a',
        boxShadow: '4px 4px 0 #16a34a',
    } as React.CSSProperties,
    conferenceStandingsTeamCell: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        minWidth: 0,
        flex: 1,
    } as React.CSSProperties,
    conferenceStandingsRank: {
        fontSize: '0.7rem',
        fontWeight: 900,
        width: '38px',
        textAlign: 'right',
        opacity: 0.9,
    } as React.CSSProperties,
    conferenceStandingsTeamLogo: {
        width: '46px',
        height: '46px',
        objectFit: 'contain',
        filter: 'drop-shadow(0 1px 0 rgba(0,0,0,0.25))',
    } as React.CSSProperties,
    conferenceStandingsTeamName: {
        fontSize: '0.65rem',
        fontWeight: 900,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        minWidth: 0,
    } as React.CSSProperties,
    conferenceStandingsStatCell: {
        width: '70px',
        textAlign: 'right',
        fontSize: '0.65rem',
        fontWeight: 900,
    } as React.CSSProperties,
    conferenceHubRow: {
        display: 'flex',
        gap: '8px',
        padding: '6px 6px',
        border: '1px solid rgba(15,23,42,0.18)',
        alignItems: 'center',
    } as React.CSSProperties,
    conferenceHubRowHighlight: {
        borderColor: '#111827',
        boxShadow: 'inset 0 0 0 2px rgba(17, 24, 39, 0.7)',
    } as React.CSSProperties,
    conferenceHubHeaderRow: {
        backgroundColor: '#e2e8f0',
        fontWeight: 'bold',
        borderColor: 'rgba(15,23,42,0.35)',
    } as React.CSSProperties,
    conferenceHubList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        fontSize: '0.55rem',
    } as React.CSSProperties,
    conferenceHubListItem: {
        borderRadius: '6px',
        border: '2px solid rgba(15,23,42,0.35)',
        backgroundColor: '#ffffff',
        padding: '8px 8px',
    } as React.CSSProperties,
    conferenceHubListItemRow: {
        display: 'flex',
        justifyContent: 'space-between',
        gap: '8px',
        alignItems: 'center',
    } as React.CSSProperties,
    conferenceHubListItemName: {
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        flex: '1 1 auto',
        minWidth: 0,
    } as React.CSSProperties,
    conferenceHubListItemValue: {
        whiteSpace: 'nowrap',
        flex: '0 0 auto',
    } as React.CSSProperties,
    conferenceHubCardGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
        gap: '10px',
    } as React.CSSProperties,
    conferenceHubCard: {
        borderRadius: '6px',
        border: '2px solid #0f172a',
        backgroundColor: '#ffffff',
        boxShadow: '2px 2px 0 #0f172a',
        padding: '8px',
        minHeight: '54px',
    } as React.CSSProperties,
    conferenceHubCardLabel: {
        fontSize: '0.45rem',
        opacity: 0.85,
        marginBottom: '6px',
    } as React.CSSProperties,
    conferenceHubCardValue: {
        fontSize: '0.75rem',
        lineHeight: 1.1,
    } as React.CSSProperties,
    conferenceHubCardValueSmall: {
        fontSize: '0.55rem',
        lineHeight: 1.1,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    } as React.CSSProperties,
    conferenceHubMeta: {
        marginTop: '6px',
        fontSize: '0.45rem',
        opacity: 0.8,
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    } as React.CSSProperties,
    conferenceHubPill: {
        display: 'inline-block',
        border: '2px solid #0f172a',
        backgroundColor: '#fef3c7',
        color: '#92400e',
        padding: '2px 4px',
        marginLeft: '6px',
        fontSize: '0.45rem',
        lineHeight: 1,
        fontWeight: 700,
    } as React.CSSProperties,
    conferenceHubEmpty: {
        fontSize: '0.55rem',
        opacity: 0.85,
        padding: '8px 6px',
    } as React.CSSProperties,
    slotContainer: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '10px',
        border: '2px solid #808080',
        marginBottom: '10px',
        backgroundColor: '#E0E0E0',
    },
    slotInfo: {
        flex: 1,
    },
    slotActions: {
        display: 'flex',
        gap: '5px',
    },
    revenueRow: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: '5px 0',
        borderBottom: '1px solid #aaa',
        fontSize: '0.7rem'
    },
    staffCard: {
        border: '2px solid #808080',
        padding: '10px',
        marginBottom: '10px',
        backgroundColor: '#E0E0E0',
        color: '#000000',
    },
    staffGrade: {
        backgroundColor: '#A0A0A0',
        padding: '3px 6px',
        fontSize: '0.6rem',
        border: '1px solid #000'
    },
    tabButton: (active: boolean): React.CSSProperties => ({
        padding: '8px 16px',
        borderRadius: '6px',
        border: `2px solid #0f172a`,
        background: active ? '#fde047' : '#ffffff',
        color: '#0f172a',
        boxShadow: active ? '2px 2px 0 #0f172a' : '2px 2px 0 rgba(15,23,42,0.35)',
        fontWeight: 800,
        fontSize: '0.9rem',
        cursor: 'pointer',
        textTransform: 'uppercase',
    }),
};

export default styles;
